// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUg7-WSvxp4szZSPo9d_PBzsWndZh-SjA',
    appId: '1:810651644664:web:7933764436ecc65d8d410d',
    messagingSenderId: '810651644664',
    projectId: 'the-dhemhi-closet',
    authDomain: 'the-dhemhi-closet.firebaseapp.com',
    storageBucket: 'the-dhemhi-closet.firebasestorage.app',
    measurementId: 'G-BHWE8KYPZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvKBnfZcafWiTLsA5VhEehrLMppivrG4',
    appId: '1:810651644664:android:45a0fe1dc6d2f6f18d410d',
    messagingSenderId: '810651644664',
    projectId: 'the-dhemhi-closet',
    storageBucket: 'the-dhemhi-closet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpGSgEHiC0pLh3L-bfQ9mwijFJHSq6hVo',
    appId: '1:810651644664:ios:4abfe7042971336d8d410d',
    messagingSenderId: '810651644664',
    projectId: 'the-dhemhi-closet',
    storageBucket: 'the-dhemhi-closet.firebasestorage.app',
    iosBundleId: 'com.example.tdbCloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpGSgEHiC0pLh3L-bfQ9mwijFJHSq6hVo',
    appId: '1:810651644664:ios:4abfe7042971336d8d410d',
    messagingSenderId: '810651644664',
    projectId: 'the-dhemhi-closet',
    storageBucket: 'the-dhemhi-closet.firebasestorage.app',
    iosBundleId: 'com.example.tdbCloset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUg7-WSvxp4szZSPo9d_PBzsWndZh-SjA',
    appId: '1:810651644664:web:b3d04b37e1d7a5fc8d410d',
    messagingSenderId: '810651644664',
    projectId: 'the-dhemhi-closet',
    authDomain: 'the-dhemhi-closet.firebaseapp.com',
    storageBucket: 'the-dhemhi-closet.firebasestorage.app',
    measurementId: 'G-3P01R4770R',
  );

}